batch_size: 64
board_loss_every: 10
devices:
- 0
embedding_size: 128
epochs: 25
gamma: 0.1
input_channel: 3
log_path: ./saved_logs/jobs/org_1_80x60
lr: 0.01
milestones:
- 10
- 15
- 22
model_type: MultiFTNet
momentum: 0.9
num_classes: 2
patch_info: org_1_80x60
save_every: 30
snapshot_dir_path: ./saved_logs/snapshot
train_root_path: ./datasets/rgb_image
