batch_size: 64
board_loss_every: 10
devices:
- 0
embedding_size: 128
epochs: 25
gamma: 0.1
input_channel: 3
log_path: ./saved_logs/jobs/test_ver_1
lr: 0.01
milestones:
- 10
- 15
- 22
model_type: MultiFTNet
momentum: 0.9
num_classes: 2
patch_info: test_ver_1
scale: 1
h_input: 80
w_input: 60
save_every: 30
snapshot_dir_path: ./saved_logs/snapshot
org_root: ./datasets/org
ft_root: ./dataset/ft